### PR TITLE
Types

### PR DESCRIPTION
**Pull request by Romulus10**
Adds a slightly-modified version of the Ethereum Secret Store data types. I think these should give us a good jumping-off point.

### CODE REVIEW

**Comment by insipx** [comment]
This looks good, but it is worth keeping in mind that the traits in `primitives/sr-primitives/src/traits.rs` may be a better place to work from. Using concrete types would work, too. It just depends on how generic we would like to be. In the end, types should be defined in the srml '`pub trait Trait` definition anyway.

**Comment by Romulus10** [comment]
To be honest, I hadn't even looked at that. So rather than defining data types native to secret store, you're recommending making direct references to Substrate primitives?

**Comment by insipx** [comment]
yes, this way it will use the types defined in the `SystemTrait` definition defined by anyone importing the crate. This makes the types consistent across the entire runtime. If a user defines a `hash` type in their `System` trait, and the SecretStore `Trait` must implement the `System` trait, you can define the SecretStore `Hash` type to be `Self::Hash`. This way, whoever uses the SecretStore Substrate Module just needs to set the hash type in their System trait for it to also be used in the SecretStore. This is preferable to constraining the hash to a concrete type that an end-user may or may not use (H256)

**Comment by Romulus10** [comment]
Alright, got it. I'm with you now. Yeah, that's wildly preferable. I'll have to do some reading on exactly how to make it happen the way we need it to.

**Pull request closed without merging**
